### PR TITLE
Calculator Program Added in file Calculator.c

### PR DESCRIPTION
**Pull request by ombhagwat2401**
Thankyou for assigning me this task

Updated Calculator.c file

Added Calculator program using C in language

Here is the Screenshot of output after executing the program

image

Please Merge my Pull Request

Suggest any changes if you want

Thankyou!

### CODE REVIEW

**Review by krishnapatidar458 — COMMENTED** [review]
the calculator will not terminate if the user does not want it to exit.
I think you got it. what I say. 
@ombhagwat2401

**Comment by ombhagwat2401** [comment]
Yes, I got it and made changes to code

Here are the output of updated code

image

**Comment by krishnapatidar458** [comment]
@ombhagwat2401 commit your updation

**Comment by ombhagwat2401** [comment]
Yes Sir

**Pull request merged**
